server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  url: http://localhost:9000

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customerservice
            predicates:
              - Path=/api/v1/individualCustomers/**
            uri: lb://customerservice
          - id: orderservice
            predicates:
              - Path=/api/orders/**
            uri: lb://orderservice
          - id: discoveryserver
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
            uri: ${eureka.url}
          - id: discoveryserver-static
            predicates:
              - Path=/eureka/**
            uri: ${eureka.url}
          - id: catalogservice
            predicates:
              - Path=/catalogservice/api/v1/products/**
              - Path=/catalogservice/api/v1/catalogs/**
            uri: lb://catalogservice
          - id: invoiceservice
            predicates:
              - Path=/api/accounts/**
            uri: lb://invoiceservice
          - id: identityservice
            predicates:
              - Path=/api/v1/auth/**
            uri: lb://identityservice