spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      mvc:
        routes:
          - id: customerservice
            predicates:
              - Path=/api/v1/individualCustomers/**
            uri: lb://customerservice
          - id: orderservice
            predicates:
              - Path=/api/v1/orders/**
            uri: lb://orderservice
          - id: discoveryserver
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
            uri: ${eureka.url}
          - id: discoveryserver-static
            predicates:
              - Path=/eureka/**
            uri: ${eureka.url}
          - id: identityservice
            predicates:
              - Path=/api/v1/auth/**
            uri: lb://identityservice
          - id: searchservice
            predicates:
              - Path=/searchservice/api/v1/catalogs/**
            uri: lb://searchService
          - id: searchservice
            predicates:
              - Path=/searchservice/api/v1/products/**
            uri: lb://searchService
          - id: searchservice
            predicates:
              - Path=/searchservice/api/v1/customers/**
            uri: lb://searchService
          - id: invoiceservice
            predicates:
              - Path=/api/v1/invoices/**
            uri: lb://invoiceservice
          - id: catalogservice
            predicates:
              - Path=/catalogservice/api/v1/catalogs/**
            uri: lb://catalogservice
          - id: accountservice
            predicates:
              - Path=/api/v1/accounts/**
            uri: lb://accountservice
          - id: cartservice
            predicates:
              - Path=/api/v1/carts/**
            uri: lb://cartservice
          - id: catalogservice
            predicates:
              - Path=/catalogservice/api/v1/products/**
            uri: lb://catalogservice

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  url: http://localhost:9000