server:
  port: 0

spring:
  data:
    mongodb:
      database: crmsearchdbprod
      host: crmsearchdbprod
      port: 27017
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://crmdiscoveryserver:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
